# This defaults to 3.5
dotnet:
    framework_version: "4.0x64"

# destination is always prefixed by build\package
# you can specify source files and/or folders to copied
# to the package location. 
packageContents:

    lib\PowerYaml:                     lib\PowerYaml
    lib\PSake:                         lib\PSake
    lib\YDeliver:                      lib\YDeliver

